# TODO @memes remove is not a golang project
# spell-checker: disable
---
name: release

# yamllint disable-line rule:truthy
on:
  push:
    tags:
      - 'v*'

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - id: setup-go
        name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - name: Execute linter
        uses: golangci/golangci-lint-action@v3.2.0
        with:
          version: latest
      - name: Install cosign
        if: ${{ success() }}
        uses: sigstore/cosign-installer@v2.5.0
      - name: Install syft
        if: ${{ success() }}
        uses: anchore/sbom-action/download-syft@v0.11.0
      - id: docker-login
        name: Login to Docker hub
        if: ${{ success() }}
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          logout: true
      - id: goreleaser
        name: Run GoReleaser
        if: ${{ success() }}
        uses: goreleaser/goreleaser-action@v3
        with:
          distribution: goreleaser
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
